// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqcywykalnmtrutsjopp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxY3l3eWthbG5tdHJ1dHNqb3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTAzNDYsImV4cCI6MjA2NTI4NjM0Nn0.VrwoIwIB4tC8oIc2SSKSaUA7MUJ-CYXsqF8CfsWyOws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);